# Generated by Django 4.1.4 on 2022-12-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="利用者")),
            ],
            options={
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名前")),
                ("last_login", models.DateTimeField(verbose_name="最終ログイン")),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=16, unique=True, verbose_name="ロール"),
                ),
                (
                    "staffs",
                    models.ManyToManyField(related_name="roles", to="app.staff"),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="配達日")),
                (
                    "mailman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.staff"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.person",
                    ),
                ),
            ],
            options={
                "db_table": "delivery",
            },
        ),
    ]
